{% set version = '0.2.12' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-chevron
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/chevron_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/chevron/chevron_{{ version }}.tar.gz
  sha256: 8f5e484034c90ac339796b78c04ffa7c6033b21bdd8a82408ae12865cbd7b0de

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    # The libstdc++.dll provided in libstdcxx v15.1.0 build h904f734_2
    # is missing `_ZSt21ios_base_library_initv`.
    # see: conda-forge/ctng-compilers-feedstock#174
    - libstdcxx !=14.3.0,!=15.1.0  # [win]
  host:
    - r-base >=4.4.0
    - r-checkmate >=2.1.0
    - r-dplyr >=1.1.0
    - r-dunlin >=0.1.10
    - r-forcats >=1.0.0
    - r-formatters >=0.5.11
    - r-ggplot2 >=3.4.0
    - r-glue >=1.0.0
    - r-lifecycle >=0.2.0
    - r-lubridate >=1.7.8
    - r-magrittr >=1.5
    - r-nestcolor >=0.1.1
    - r-purrr >=0.3.0
    - r-rlang >=1.0.0
    - r-rlistings >=0.2.12
    - r-rtables >=0.6.13
    - r-stringr >=1.4.1
    - r-tern >=0.9.9
    - r-tibble >=2.0.0
  run:
    - r-base >=4.4.0
    - r-checkmate >=2.1.0
    - r-dplyr >=1.1.0
    - r-dunlin >=0.1.10
    - r-forcats >=1.0.0
    - r-formatters >=0.5.11
    - r-ggplot2 >=3.4.0
    - r-glue >=1.0.0
    - r-lifecycle >=0.2.0
    - r-lubridate >=1.7.8
    - r-magrittr >=1.5
    - r-nestcolor >=0.1.1
    - r-purrr >=0.3.0
    - r-rlang >=1.0.0
    - r-rlistings >=0.2.12
    - r-rtables >=0.6.13
    - r-stringr >=1.4.1
    - r-tern >=0.9.9
    - r-tibble >=2.0.0
  run_constrained:
    - libstdcxx !=14.3.0,!=15.1.0           # [win]

test:
  commands:
    - $R -e "library('chevron')"           # [not win]
    - "\"%R%\" -e \"library('chevron')\""  # [win]

about:
  home: https://insightsengineering.github.io/chevron/, https://github.com/insightsengineering/chevron/
  license: Apache-2.0
  summary: Provide standard tables, listings, and graphs (TLGs) libraries used in clinical trials.
    This package implements a structure to reformat the data with 'dunlin', create reporting
    tables using 'rtables' and 'tern' with standardized input arguments to enable quick
    generation of standard outputs.  In addition, it also provides comprehensive data
    checks and script generation functionality.
  license_family: APACHE
  license_file:
    - LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r
